### ISSUE TITLE
Property 'map' does not exist on type 'Observable<Response>

### ISSUE THREAD

**Issue by yashwp** [SamirHodzic/ngx-embed-video#14]
This library is Not working with Angular 6 due to change in the directory structure of the RxJs.

ERROR in node_modules/ngx-embed-video/src/embed-video.service.ts(147,8): error TS2339: Property 'map' does not exist on type 'Observable<Response>'.
node_modules/ngx-embed-video/src/embed-video.service.ts(167,8): error TS2339: Property 'map' does not exist on type 'Observable<Response>'.

**Comment by IsaacSomething** [comment]
`rxjs` update issue no doubt.
https://www.academind.com/learn/javascript/rxjs-6-what-changed/

I think a few libraries have bit hit by this

**Comment by SamirHodzic** [comment]
Should be fine with https://github.com/SamirHodzic/ngx-embed-video/pull/16m let me know if problem still exists.
