### ISSUE TITLE
Update Angular to latest stable version (4.4.4)

### ISSUE THREAD

**Issue by SamirHodzic** [SamirHodzic/ngx-embed-video#2]
Also be sure that everything works fine with updated version.

**Comment by excelulous** [comment]
I took a look at this. No changes needed to the core TS files, just some tweaks to package.json and tsconfig.json. I'll open a PR in a few moments.

**Comment by excelulous** [comment]
PR - #4

**Comment by SamirHodzic** [comment]
Thanks.
