### ISSUE TITLE
Iframe sizes on diferent resolutions and devices

### ISSUE THREAD

**Issue by darkMT** [SamirHodzic/ngx-embed-video#20]
Hi Guys,

I really like your plugin but the only thing that I cant display an image thumb as it is giving me the {{ object.promise }} even when I store the result in a variable like this
```let thumb_1 = this.embedService.embed_image(value.firstVideo);```

and in the template i use:
```<span [innerHtml]="battle.thumbOne"></span>```

**Comment by SamirHodzic** [comment]
Hi @darkMT,

Sorry, readme is not clear enough about it, will update.
It is using promise, so to get the resolved value you need to use `then` callback function.

```typescript
this.embedService.embed_image(value.firstVideo).then((res) => { 
  this.thumbnail = res.html;
});
```

**Comment by darkMT** [comment]
Thanks/Hvala Samir,

I have already done that :)

**Comment by SamirHodzic** [comment]
Awesome 👍
