### ISSUE TITLE
How to handle error in the Youtube URL 

### ISSUE THREAD

**Issue by saicharanbollampally** [SamirHodzic/ngx-embed-video#24]
this.embedService.embed(this.exercise.YoutubeUrl, {
  query: { portrait: 0, color: 'black' },
  attr: { width: 800, height: 380, frameborder:1 }
}).then(res => {
    this.iframeURL = res.html;
  });

Error: 
this.embedService.embed(...).then is not a function

**Comment by SamirHodzic** [comment]
You mixed `embed` and `embed_image` usage. 
`embed` function doesn't have callback.

```typescript
this.iframeURL = this.embedService.embed(this.exercise.YoutubeUrl, {
    query: { portrait: 0, color: 'black' },
    attr: { width: 800, height: 380, frameborder:1 }
});
```
