### ISSUE TITLE
How to implement ngx-embed-video with ngx-slick-carousel

### ISSUE THREAD

**Issue by NikitaPooja** [SamirHodzic/ngx-embed-video#27]

**Comment by SamirHodzic** [comment]
Not sure about usage for `ngx-slick-carousel`, never used it before. Can you give me concrete example with combination of those two plugins together?

**Comment by NikitaPooja** [comment]
I want to use video on the slider. ngx-slick-carousel package is used for
slider and ngx-emebed-video for video displaye. so I want to use both
packages . please check the screenshot
