### ISSUE TITLE
Angular 7.x support

### ISSUE THREAD

**Issue by Eraldo** [SamirHodzic/ngx-embed-video#29]
I am using this package with angular 7.2.13.
Judging from my perspective it does seem to work.

When I do `npm i` I get a warning:
`ngx-embed-video@1.0.4 requires a peer of @angular/core@^6.0.0`

I am wondering why it is kept at `@angular/core@^6.0.0`.
Any ideas?

**Comment by SamirHodzic** [comment]
To support 6.x+ versions, currently peerDependencies are defined as 6.0.0 min version. Probably will updated soon to 7+.

**Comment by Eraldo** [comment]
Thank you @SamirHodzic for the update.
I appreciate it. ;)
