### ISSUE TITLE
Some Angular 5 / Typescript issues

### ISSUE THREAD

**Issue by mwawrusch** [SamirHodzic/ngx-embed-video#5]
ERROR in node_modules/ngx-embed-video/src/embed-video.service.ts(205,26): error TS2345: Argument of type 'string' is notassignable to parameter of type 'never'.
node_modules/ngx-embed-video/src/embed-video.service.ts(229,5): error TS2322: Type 'null' is not assignable to type 'string'.
node_modules/ngx-embed-video/src/embed-video.service.ts(241,5): error TS2322: Type 'null' is not assignable to type 'string'.

**Comment by SamirHodzic** [comment]
By default `angular-cli` is not generating `tsconfig` with `strictNullChecks: true`.
Thanks for pointing this out, fixed per 6e1c0731f49b29ec7a48b10d008e05ebfa6c861d.

**Comment by mwawrusch** [comment]
thx
