### ISSUE TITLE
Can't find module @angular/Http

### ISSUE THREAD

**Issue by mcblum** [SamirHodzic/ngx-embed-video#6]
Hello! It looks like the package is using an older version of the HTTP client. Here's the exact message:

`ERROR in node_modules/ngx-embed-video/dist/src/embed-video.service.d.ts(1,22): error TS2307: Cannot find module '@angular/http'.`

I think that needs to be updated to `HttpClient`, but I'm not totally sure. I'm going to try to hack at it for now but if you have a chance to take a look I'd really appreciated it!

Matt

**Comment by mcblum** [comment]
Ok, did some quick tests, that is, in fact, the issue. For anyone else that comes across this `@angular/http` was depreciated and is no longer included with Angular > 5 new applications. The new package is part of `HttpClientModule`. However, you can always `yarn add @angular/http` to make this work.

**Comment by SamirHodzic** [comment]
Hi, I'm already aware of this, main reason why I still didn't migrated package fully to Angular ^5.
Will check it out soon when I catch time.

**Comment by SamirHodzic** [comment]
Currently, don't have time to play with it. 
If you have time to update it and test if it works fine with latest Angular, feel free to make a pull request.

**Comment by mmoravcik** [comment]
Pull request is ready, but not accepted...

**Comment by SamirHodzic** [comment]
Should be fine with #16, let me know if problem still exists.
