### ISSUE TITLE
Bug with cordova (ionic) url protocol

### ISSUE THREAD

**Issue by Nightbr** [SamirHodzic/ngx-embed-video#9]
Hey,

I have an issue with the url protocol of video. In your code, you set url `src="//www.youtube.com/embed/`but in mobile app with cordova, the protocol is `file://` so it throw an error...

I think today `https` is a requirement everywhere so we can just hardcoded `src="https://www.youtube.com/embed/` in this lib.

If you're not agree with this, we can create a parameter to set the protocol manually and use it when it is set.

Let me know what do you want and I will create a PR ASAP.

![image](https://user-images.githubusercontent.com/4228646/37030629-e704c062-213b-11e8-8883-b1192713072c.png)

Thanks!

**Comment by SamirHodzic** [comment]
Yes, ```https``` is kinda main for those video streaming services. Thanks, will check out PR. 👍

**Comment by SamirHodzic** [comment]
Closing per https://github.com/SamirHodzic/ngx-embed-video/pull/10.
